# This file is (or will be) autogenerated. Modify at your own peril!
#!/system/bin/sh

echo "/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:17/wakeup/wakeup23/max_time_ms"
cat /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:17/wakeup/wakeup23/max_time_ms > /dev/null
echo "/proc/asound/card0/id"
/data/local/tmp/kflattest WRITE "/proc/asound/card0/id" "0"
