# This file is autogenerated. Modify at your own peril!
#!/system/bin/sh

## Interface triggers for write

echo "[1/205] WRITE: /sys/power/wake_unlock [wake_unlock_store]"
/data/local/tmp/kflattest WRITE "/sys/power/wake_unlock" "0"

echo "[2/205] WRITE: /sys/power/pm_async [pm_async_store]"
/data/local/tmp/kflattest WRITE "/sys/power/pm_async" "0"

echo "[3/205] WRITE: /sys/devices/platform/dummy_udc.0/udc/dummy_udc.0/soft_connect [soft_connect_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/dummy_udc.0/udc/dummy_udc.0/soft_connect" "0"

echo "[4/205] WRITE: /sys/devices/platform/dummy_udc.0/udc/dummy_udc.0/srp [srp_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/dummy_udc.0/udc/dummy_udc.0/srp" "0"

echo "[5/205] WRITE: /sys/module/acpi/parameters/aml_debug_output [param_set_byte]"
/data/local/tmp/kflattest WRITE "/sys/module/acpi/parameters/aml_debug_output" "0"

echo "[6/205] WRITE: /sys/devices/platform/i8042/serio0/scroll [atkbd_do_set_scroll]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/i8042/serio0/scroll" "0"

echo "[7/205] WRITE: /sys/devices/virtual/block/zram0/compact [compact_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/block/zram0/compact" "0"

echo "[8/205] WRITE: /sys/devices/virtual/thermal/thermal_zone0/k_d [k_d_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/thermal/thermal_zone0/k_d" "0"

echo "[9/205] WRITE: /sys/devices/virtual/bdi/253:2/min_ratio [min_ratio_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/bdi/253:2/min_ratio" "0"

echo "[10/205] WRITE: /sys/module/block/parameters/events_dfl_poll_msecs [disk_events_set_dfl_poll_msecs]"
/data/local/tmp/kflattest WRITE "/sys/module/block/parameters/events_dfl_poll_msecs" "0"

echo "[11/205] WRITE: /sys/kernel/slab/dma-kmalloc-512/ctor [slab_attr_store]"
/data/local/tmp/kflattest WRITE "/sys/kernel/slab/dma-kmalloc-512/ctor" "0"

echo "[12/205] WRITE: /sys/devices/virtual/net/gre0/queues/tx-0/byte_queue_limits/hold_time [bql_set_hold_time]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/net/gre0/queues/tx-0/byte_queue_limits/hold_time" "0"

echo "[13/205] WRITE: /sys/class/firmware/timeout [timeout_store]"
/data/local/tmp/kflattest WRITE "/sys/class/firmware/timeout" "0"

echo "[14/205] WRITE: /dev/full [write_full]"
/data/local/tmp/kflattest WRITE "/dev/full" "0"

echo "[15/205] WRITE: /sys/devices/virtual/block/loop21/events_poll_msecs [disk_events_poll_msecs_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/block/loop21/events_poll_msecs" "0"

echo "[16/205] WRITE: /sys/kernel/tracing/free_buffer [tracing_free_buffer_write]"
/data/local/tmp/kflattest WRITE "/sys/kernel/tracing/free_buffer" "0"

echo "[17/205] WRITE: /sys/power/wake_lock [wake_lock_store]"
/data/local/tmp/kflattest WRITE "/sys/power/wake_lock" "0"

echo "[18/205] WRITE: /sys/devices/platform/i8042/serio0/softraw [atkbd_do_set_softraw]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/i8042/serio0/softraw" "0"

echo "[19/205] WRITE: /sys/module/hid_steam/parameters/lizard_mode [steam_param_set_lizard_mode]"
/data/local/tmp/kflattest WRITE "/sys/module/hid_steam/parameters/lizard_mode" "0"

echo "[20/205] WRITE: /sys/devices/virtual/block/ram0/queue/iostats [queue_store_iostats]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/block/ram0/queue/iostats" "0"

echo "[21/205] WRITE: /sys/kernel/tracing/per_cpu/cpu1/trace [tracing_write_stub]"
/data/local/tmp/kflattest WRITE "/sys/kernel/tracing/per_cpu/cpu1/trace" "0"

echo "[22/205] WRITE: /sys/module/usb_storage/parameters/delay_use [param_set_uint]"
/data/local/tmp/kflattest WRITE "/sys/module/usb_storage/parameters/delay_use" "0"

echo "[23/205] WRITE: /config/usb_gadget/g1/bMaxPacketSize0 [gadget_dev_desc_bMaxPacketSize0_store]"
/data/local/tmp/kflattest WRITE "/config/usb_gadget/g1/bMaxPacketSize0" "0"

echo "[24/205] WRITE: /sys/devices/pci0000:00/0000:00:15.0/broken_parity_status [broken_parity_status_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/pci0000:00/0000:00:15.0/broken_parity_status" "0"

echo "[25/205] WRITE: /sys/devices/system/machinecheck/machinecheck1/bank8 [set_bank]"
/data/local/tmp/kflattest WRITE "/sys/devices/system/machinecheck/machinecheck1/bank8" "0"

echo "[26/205] WRITE: /sys/module/button/parameters/lid_init_state [param_set_lid_init_state]"
/data/local/tmp/kflattest WRITE "/sys/module/button/parameters/lid_init_state" "0"

echo "[27/205] WRITE: /sys/devices/platform/rtc-test.1/rtc/rtc2/wakealarm [wakealarm_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/rtc-test.1/rtc/rtc2/wakealarm" "0"

echo "[28/205] WRITE: /config/usb_gadget/g1/bcdUSB [gadget_dev_desc_bcdUSB_store]"
/data/local/tmp/kflattest WRITE "/config/usb_gadget/g1/bcdUSB" "0"

echo "[29/205] WRITE: /sys/devices/virtual/net/sit0/ifalias [ifalias_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/net/sit0/ifalias" "0"

echo "[30/205] WRITE: /sys/module/snd_hda_intel/parameters/model [module_attr_store]"
/data/local/tmp/kflattest WRITE "/sys/module/snd_hda_intel/parameters/model" "0"

echo "[31/205] WRITE: /proc/pressure/cpu [psi_cpu_write]"
/data/local/tmp/kflattest WRITE "/proc/pressure/cpu" "0"

echo "[32/205] WRITE: /sys/module/dm_bufio/parameters/retain_bytes [param_set_ulong]"
/data/local/tmp/kflattest WRITE "/sys/module/dm_bufio/parameters/retain_bytes" "0"

echo "[33/205] WRITE: /sys/devices/virtual/block/loop9/queue/io_poll_delay [queue_poll_delay_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/block/loop9/queue/io_poll_delay" "0"

echo "[34/205] WRITE: /sys/module/nf_conntrack/parameters/hashsize [nf_conntrack_set_hashsize]"
/data/local/tmp/kflattest WRITE "/sys/module/nf_conntrack/parameters/hashsize" "0"

echo "[35/205] WRITE: /config/usb_gadget/g1/bDeviceSubClass [gadget_dev_desc_bDeviceSubClass_store]"
/data/local/tmp/kflattest WRITE "/config/usb_gadget/g1/bDeviceSubClass" "0"

echo "[36/205] WRITE: /sys/devices/pnp0/00:04/tty/ttyS0/rx_trig_bytes [serial8250_set_attr_rx_trig_bytes]"
/data/local/tmp/kflattest WRITE "/sys/devices/pnp0/00:04/tty/ttyS0/rx_trig_bytes" "0"

echo "[37/205] WRITE: /sys/devices/virtual/thermal/thermal_zone0/k_i [k_i_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/thermal/thermal_zone0/k_i" "0"

echo "[38/205] WRITE: /sys/devices/virtual/block/zram0/comp_algorithm [comp_algorithm_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/block/zram0/comp_algorithm" "0"

echo "[39/205] WRITE: /sys/devices/pci0000:00/0000:00:00.0/config [pci_write_config]"
/data/local/tmp/kflattest WRITE "/sys/devices/pci0000:00/0000:00:00.0/config" "0"

echo "[40/205] WRITE: /sys/devices/virtual/block/zram0/mem_used_max [mem_used_max_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/block/zram0/mem_used_max" "0"

echo "[41/205] WRITE: /sys/kernel/rcu_expedited [rcu_expedited_store]"
/data/local/tmp/kflattest WRITE "/sys/kernel/rcu_expedited" "0"

echo "[42/205] WRITE: /sys/module/module/parameters/sig_enforce [param_set_bool_enable_only]"
/data/local/tmp/kflattest WRITE "/sys/module/module/parameters/sig_enforce" "0"

echo "[43/205] WRITE: /sys/module/pcie_aspm/parameters/policy [pcie_aspm_set_policy]"
/data/local/tmp/kflattest WRITE "/sys/module/pcie_aspm/parameters/policy" "0"

echo "[44/205] WRITE: /sys/devices/virtual/net/lo/queues/tx-0/tx_maxrate [tx_maxrate_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/net/lo/queues/tx-0/tx_maxrate" "0"

echo "[45/205] WRITE: /sys/devices/platform/rtc-test.0/rtc/rtc1/max_user_freq [max_user_freq_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/rtc-test.0/rtc/rtc1/max_user_freq" "0"

echo "[46/205] WRITE: /sys/devices/virtual/block/ram1/queue/rotational [queue_store_nonrot]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/block/ram1/queue/rotational" "0"

echo "[47/205] WRITE: /proc/acpi/wakeup [acpi_system_write_wakeup_device]"
/data/local/tmp/kflattest WRITE "/proc/acpi/wakeup" "0"

echo "[48/205] WRITE: /sys/kernel/slab/RAWv6/red_zone [red_zone_store]"
/data/local/tmp/kflattest WRITE "/sys/kernel/slab/RAWv6/red_zone" "0"

echo "[49/205] WRITE: /sys/devices/virtual/block/dm-3/queue/read_ahead_kb [queue_ra_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/block/dm-3/queue/read_ahead_kb" "0"

echo "[50/205] WRITE: /sys/devices/virtual/thermal/thermal_zone0/k_po [k_po_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/thermal/thermal_zone0/k_po" "0"

echo "[51/205] WRITE: /sys/fs/selinux/checkreqprot [sel_write_checkreqprot]"
/data/local/tmp/kflattest WRITE "/sys/fs/selinux/checkreqprot" "0"

echo "[52/205] WRITE: /sys/module/overlay/parameters/check_copy_up [ovl_ccup_set]"
/data/local/tmp/kflattest WRITE "/sys/module/overlay/parameters/check_copy_up" "0"

echo "[53/205] WRITE: /proc/uid_cputime/remove_uid_range [uid_remove_write]"
/data/local/tmp/kflattest WRITE "/proc/uid_cputime/remove_uid_range" "0"

echo "[54/205] WRITE: /sys/kernel/slab/kmalloc-rcl-2k/shrink [shrink_store]"
/data/local/tmp/kflattest WRITE "/sys/kernel/slab/kmalloc-rcl-2k/shrink" "0"

echo "[55/205] WRITE: /sys/devices/system/container/PNP0A06:00/online [online_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/system/container/PNP0A06:00/online" "0"

echo "[56/205] WRITE: /sys/module/rcutree/parameters/jiffies_till_next_fqs [param_set_next_fqs_jiffies]"
/data/local/tmp/kflattest WRITE "/sys/module/rcutree/parameters/jiffies_till_next_fqs" "0"

echo "[57/205] WRITE: /sys/module/snd_hda_intel/parameters/align_buffer_size [param_set_bint]"
/data/local/tmp/kflattest WRITE "/sys/module/snd_hda_intel/parameters/align_buffer_size" "0"

echo "[58/205] WRITE: /sys/kernel/slab/PINGv6/trace [trace_store]"
/data/local/tmp/kflattest WRITE "/sys/kernel/slab/PINGv6/trace" "0"

echo "[59/205] WRITE: /config/usb_gadget/g1/idVendor [gadget_dev_desc_idVendor_store]"
/data/local/tmp/kflattest WRITE "/config/usb_gadget/g1/idVendor" "0"

echo "[60/205] WRITE: /sys/firmware/acpi/hotplug/force_remove [force_remove_store]"
/data/local/tmp/kflattest WRITE "/sys/firmware/acpi/hotplug/force_remove" "0"

echo "[61/205] WRITE: /sys/devices/platform/dummy_hcd.0/usb1/power/level [level_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/dummy_hcd.0/usb1/power/level" "0"

echo "[62/205] WRITE: /sys/devices/pci0000:00/0000:00:02.0/sound/card0/id [card_id_store_attr]"
/data/local/tmp/kflattest WRITE "/sys/devices/pci0000:00/0000:00:02.0/sound/card0/id" "0"

echo "[63/205] WRITE: /sys/devices/virtual/block/ram5/queue/max_sectors_kb [queue_max_sectors_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/block/ram5/queue/max_sectors_kb" "0"

echo "[64/205] WRITE: /sys/kernel/tracing/tracing_thresh [tracing_thresh_write]"
/data/local/tmp/kflattest WRITE "/sys/kernel/tracing/tracing_thresh" "0"

echo "[65/205] WRITE: /sys/devices/system/machinecheck/machinecheck1/ignore_ce [set_ignore_ce]"
/data/local/tmp/kflattest WRITE "/sys/devices/system/machinecheck/machinecheck1/ignore_ce" "0"

echo "[66/205] WRITE: /sys/devices/system/clocksource/clocksource0/current_clocksource [current_clocksource_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/system/clocksource/clocksource0/current_clocksource" "0"

echo "[67/205] WRITE: /sys/devices/platform/dummy_hcd.0/usb1/1-0:1.0/usb1-port1/quirks [quirks_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/dummy_hcd.0/usb1/1-0:1.0/usb1-port1/quirks" "0"

echo "[68/205] WRITE: /sys/kernel/rcu_normal [rcu_normal_store]"
/data/local/tmp/kflattest WRITE "/sys/kernel/rcu_normal" "0"

echo "[69/205] WRITE: /sys/devices/system/clocksource/clocksource0/unbind_clocksource [unbind_clocksource_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/system/clocksource/clocksource0/unbind_clocksource" "0"

echo "[70/205] WRITE: /sys/devices/platform/i8042/serio0/set [atkbd_do_set_set]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/i8042/serio0/set" "0"

echo "[71/205] WRITE: /config/usb_gadget/g1/bDeviceClass [gadget_dev_desc_bDeviceClass_store]"
/data/local/tmp/kflattest WRITE "/config/usb_gadget/g1/bDeviceClass" "0"

echo "[72/205] WRITE: /sys/kernel/slab/zspage/sanity_checks [sanity_checks_store]"
/data/local/tmp/kflattest WRITE "/sys/kernel/slab/zspage/sanity_checks" "0"

echo "[73/205] WRITE: /proc/pressure/memory [psi_memory_write]"
/data/local/tmp/kflattest WRITE "/proc/pressure/memory" "0"

echo "[74/205] WRITE: /sys/kernel/tracing/dynamic_events [dyn_event_write]"
/data/local/tmp/kflattest WRITE "/sys/kernel/tracing/dynamic_events" "0"

echo "[75/205] WRITE: /proc/asound/card0/id [snd_info_text_entry_write]"
/data/local/tmp/kflattest WRITE "/proc/asound/card0/id" "0"

echo "[76/205] WRITE: /sys/fs/selinux/relabel [selinux_transaction_write]"
/data/local/tmp/kflattest WRITE "/sys/fs/selinux/relabel" "0"

echo "[77/205] WRITE: /config/usb_gadget/g1/os_desc/use [os_desc_use_store]"
/data/local/tmp/kflattest WRITE "/config/usb_gadget/g1/os_desc/use" "0"

echo "[78/205] WRITE: /dev/cpu_dma_latency [pm_qos_power_write]"
/data/local/tmp/kflattest WRITE "/dev/cpu_dma_latency" "0"

echo "[79/205] WRITE: /proc/slabinfo [slabinfo_write]"
/data/local/tmp/kflattest WRITE "/proc/slabinfo" "0"

echo "[80/205] WRITE: /sys/devices/platform/dummy_hcd.0/usb1/authorized_default [authorized_default_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/dummy_hcd.0/usb1/authorized_default" "0"

echo "[81/205] WRITE: /sys/module/scsi_mod/parameters/scan [param_set_copystring]"
/data/local/tmp/kflattest WRITE "/sys/module/scsi_mod/parameters/scan" "0"

echo "[82/205] WRITE: /sys/devices/pci0000:00/0000:00:04.0/resource2 [pci_write_resource_io]"
/data/local/tmp/kflattest WRITE "/sys/devices/pci0000:00/0000:00:04.0/resource2" "0"

echo "[83/205] WRITE: /sys/module/serdev_ttyport/parameters/pdev_tty_port [param_set_charp]"
/data/local/tmp/kflattest WRITE "/sys/module/serdev_ttyport/parameters/pdev_tty_port" "0"

echo "[84/205] WRITE: /sys/devices/pci0000:00/0000:00:08.0/rom [pci_write_rom]"
/data/local/tmp/kflattest WRITE "/sys/devices/pci0000:00/0000:00:08.0/rom" "0"

echo "[85/205] WRITE: /sys/kernel/slab/skbuff_fclone_cache/order [order_store]"
/data/local/tmp/kflattest WRITE "/sys/kernel/slab/skbuff_fclone_cache/order" "0"

echo "[86/205] WRITE: /sys/devices/virtual/bdi/7:128/read_ahead_kb [read_ahead_kb_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/bdi/7:128/read_ahead_kb" "0"

echo "[87/205] WRITE: /sys/devices/virtual/thermal/thermal_zone0/sustainable_power [sustainable_power_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/thermal/thermal_zone0/sustainable_power" "0"

echo "[88/205] WRITE: /config/usb_gadget/g1/os_desc/b_vendor_code [os_desc_b_vendor_code_store]"
/data/local/tmp/kflattest WRITE "/config/usb_gadget/g1/os_desc/b_vendor_code" "0"

echo "[89/205] WRITE: /sys/devices/virtual/net/ip6gre0/flags [flags_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/net/ip6gre0/flags" "0"

echo "[90/205] WRITE: /sys/devices/system/machinecheck/machinecheck0/cmci_disabled [set_cmci_disabled]"
/data/local/tmp/kflattest WRITE "/sys/devices/system/machinecheck/machinecheck0/cmci_disabled" "0"

echo "[91/205] WRITE: /sys/module/acpi/parameters/ec_event_clearing [param_set_event_clearing]"
/data/local/tmp/kflattest WRITE "/sys/module/acpi/parameters/ec_event_clearing" "0"

echo "[92/205] WRITE: /sys/devices/system/machinecheck/machinecheck0/check_interval [store_int_with_restart]"
/data/local/tmp/kflattest WRITE "/sys/devices/system/machinecheck/machinecheck0/check_interval" "0"

echo "[93/205] WRITE: /sys/firmware/acpi/hotplug/processor/enabled [hotplug_enabled_store]"
/data/local/tmp/kflattest WRITE "/sys/firmware/acpi/hotplug/processor/enabled" "0"

echo "[94/205] WRITE: /sys/fs/selinux/validatetrans [sel_write_validatetrans]"
/data/local/tmp/kflattest WRITE "/sys/fs/selinux/validatetrans" "0"

echo "[95/205] WRITE: /sys/module/rcutree/parameters/jiffies_till_first_fqs [param_set_first_fqs_jiffies]"
/data/local/tmp/kflattest WRITE "/sys/module/rcutree/parameters/jiffies_till_first_fqs" "0"

echo "[96/205] WRITE: /sys/devices/virtual/block/ram14/queue/add_random [queue_store_random]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/block/ram14/queue/add_random" "0"

echo "[97/205] WRITE: /sys/class/zram-control/hot_add [class_attr_store]"
/data/local/tmp/kflattest WRITE "/sys/class/zram-control/hot_add" "0"

echo "[98/205] WRITE: /sys/devices/pci0000:00/0000:00:06.0/msi_bus [msi_bus_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/pci0000:00/0000:00:06.0/msi_bus" "0"

echo "[99/205] WRITE: /sys/devices/platform/serial8250/tty/ttyS2/power/wakeup [wakeup_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/serial8250/tty/ttyS2/power/wakeup" "0"

echo "[100/205] WRITE: /proc/irq/default_smp_affinity [default_affinity_write]"
/data/local/tmp/kflattest WRITE "/proc/irq/default_smp_affinity" "0"

echo "[101/205] WRITE: /sys/devices/virtual/block/zram0/idle [idle_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/block/zram0/idle" "0"

echo "[102/205] WRITE: /sys/devices/platform/GFSH0001:00/power_supply/battery/cycle_count [power_supply_store_property]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/GFSH0001:00/power_supply/battery/cycle_count" "0"

echo "[103/205] WRITE: /sys/devices/platform/i8042/serio0/softrepeat [atkbd_do_set_softrepeat]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/i8042/serio0/softrepeat" "0"

echo "[104/205] WRITE: /sys/devices/virtual/block/zram0/max_comp_streams [max_comp_streams_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/block/zram0/max_comp_streams" "0"

echo "[105/205] WRITE: /sys/bus/serio/drivers/atkbd/description [drv_attr_store]"
/data/local/tmp/kflattest WRITE "/sys/bus/serio/drivers/atkbd/description" "0"

echo "[106/205] WRITE: /sys/devices/virtual/net/ip6gre0/queues/tx-0/byte_queue_limits/limit [bql_set_limit]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/net/ip6gre0/queues/tx-0/byte_queue_limits/limit" "0"

echo "[107/205] WRITE: /sys/devices/system/machinecheck/machinecheck0/dont_log_ce [device_store_bool]"
/data/local/tmp/kflattest WRITE "/sys/devices/system/machinecheck/machinecheck0/dont_log_ce" "0"

echo "[108/205] WRITE: /sys/power/pm_freeze_timeout [pm_freeze_timeout_store]"
/data/local/tmp/kflattest WRITE "/sys/power/pm_freeze_timeout" "0"

echo "[109/205] WRITE: /sys/devices/virtual/workqueue/writeback/max_active [max_active_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/workqueue/writeback/max_active" "0"

echo "[110/205] WRITE: /sys/bus/serio/drivers/atkbd/bind_mode [bind_mode_store]"
/data/local/tmp/kflattest WRITE "/sys/bus/serio/drivers/atkbd/bind_mode" "0"

echo "[111/205] WRITE: /sys/devices/pnp0/00:00/cmos_nvram0/nvmem [bin_attr_nvmem_write]"
/data/local/tmp/kflattest WRITE "/sys/devices/pnp0/00:00/cmos_nvram0/nvmem" "0"

echo "[112/205] WRITE: /sys/fs/selinux/avc/cache_threshold [sel_write_avc_cache_threshold]"
/data/local/tmp/kflattest WRITE "/sys/fs/selinux/avc/cache_threshold" "0"

echo "[113/205] WRITE: /sys/devices/virtual/net/erspan0/gro_flush_timeout [gro_flush_timeout_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/net/erspan0/gro_flush_timeout" "0"

echo "[114/205] WRITE: /proc/uid_procstat/set [uid_procstat_write]"
/data/local/tmp/kflattest WRITE "/proc/uid_procstat/set" "0"

echo "[115/205] WRITE: /sys/devices/pci0000:00/0000:00:09.0/enable [enable_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/pci0000:00/0000:00:09.0/enable" "0"

echo "[116/205] WRITE: /sys/kernel/slab/nf_conncount_tuple/min_partial [min_partial_store]"
/data/local/tmp/kflattest WRITE "/sys/kernel/slab/nf_conncount_tuple/min_partial" "0"

echo "[117/205] WRITE: /dev/vga_arbiter [vga_arb_write]"
/data/local/tmp/kflattest WRITE "/dev/vga_arbiter" "0"

echo "[118/205] WRITE: /proc/bus/pci/00/13.0 [proc_bus_pci_write]"
/data/local/tmp/kflattest WRITE "/proc/bus/pci/00/13.0" "0"

echo "[119/205] WRITE: /sys/devices/platform/dummy_hcd.0/usb1/power/autosuspend [autosuspend_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/dummy_hcd.0/usb1/power/autosuspend" "0"

echo "[120/205] WRITE: /sys/devices/virtual/net/ip6gre0/queues/tx-0/xps_cpus [xps_cpus_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/net/ip6gre0/queues/tx-0/xps_cpus" "0"

echo "[121/205] WRITE: /sys/devices/system/cpu/cpu0/power/pm_qos_resume_latency_us [pm_qos_resume_latency_us_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/system/cpu/cpu0/power/pm_qos_resume_latency_us" "0"

echo "[122/205] WRITE: /sys/devices/pci0000:00/0000:00:05.0/virtio2/block/vdc/queue/rq_affinity [queue_rq_affinity_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/pci0000:00/0000:00:05.0/virtio2/block/vdc/queue/rq_affinity" "0"

echo "[123/205] WRITE: /sys/class/zram-control/hot_remove [hot_remove_store]"
/data/local/tmp/kflattest WRITE "/sys/class/zram-control/hot_remove" "0"

echo "[124/205] WRITE: /sys/devices/virtual/thermal/cooling_device0/cur_state [cur_state_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/thermal/cooling_device0/cur_state" "0"

echo "[125/205] WRITE: /sys/kernel/tracing/events/virtio_gpu/filter [subsystem_filter_write]"
/data/local/tmp/kflattest WRITE "/sys/kernel/tracing/events/virtio_gpu/filter" "0"

echo "[126/205] WRITE: /sys/devices/virtual/block/loop2/queue/discard_max_bytes [queue_discard_max_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/block/loop2/queue/discard_max_bytes" "0"

echo "[127/205] WRITE: /dev/rfkill [rfkill_fop_write]"
/data/local/tmp/kflattest WRITE "/dev/rfkill" "0"

echo "[128/205] WRITE: /sys/devices/virtual/thermal/thermal_zone0/policy [policy_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/thermal/thermal_zone0/policy" "0"

echo "[129/205] WRITE: /sys/devices/virtual/block/loop26/queue/nomerges [queue_nomerges_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/block/loop26/queue/nomerges" "0"

echo "[130/205] WRITE: /sys/module/hid_logitech_hidpp/parameters/disable_raw_mode [param_set_bool]"
/data/local/tmp/kflattest WRITE "/sys/module/hid_logitech_hidpp/parameters/disable_raw_mode" "0"

echo "[131/205] WRITE: /sys/devices/virtual/net/ip6tnl0/tx_queue_len [tx_queue_len_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/net/ip6tnl0/tx_queue_len" "0"

echo "[132/205] WRITE: /sys/module/usbcore/parameters/quirks [quirks_param_set]"
/data/local/tmp/kflattest WRITE "/sys/module/usbcore/parameters/quirks" "0"

echo "[133/205] WRITE: /config/usb_gadget/g1/bDeviceProtocol [gadget_dev_desc_bDeviceProtocol_store]"
/data/local/tmp/kflattest WRITE "/config/usb_gadget/g1/bDeviceProtocol" "0"

echo "[134/205] WRITE: /sys/devices/platform/i8042/serio0/extra [atkbd_do_set_extra]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/i8042/serio0/extra" "0"

echo "[135/205] WRITE: /sys/devices/virtual/bdi/1:13/max_ratio [max_ratio_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/bdi/1:13/max_ratio" "0"

echo "[136/205] WRITE: /sys/devices/platform/i8042/serio1/drvctl [drvctl_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/i8042/serio1/drvctl" "0"

echo "[137/205] WRITE: /sys/module/rcutree/parameters/rcu_resched_ns [param_set_long]"
/data/local/tmp/kflattest WRITE "/sys/module/rcutree/parameters/rcu_resched_ns" "0"

echo "[138/205] WRITE: /config/usb_gadget/g1/bcdDevice [gadget_dev_desc_bcdDevice_store]"
/data/local/tmp/kflattest WRITE "/config/usb_gadget/g1/bcdDevice" "0"

echo "[139/205] WRITE: /sys/devices/platform/i8042/serio0/force_release [atkbd_do_set_force_release]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/i8042/serio0/force_release" "0"

echo "[140/205] WRITE: /sys/power/wakeup_count [wakeup_count_store]"
/data/local/tmp/kflattest WRITE "/sys/power/wakeup_count" "0"

echo "[141/205] WRITE: /sys/devices/virtual/block/loop7/queue/io_poll [queue_poll_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/block/loop7/queue/io_poll" "0"

echo "[142/205] WRITE: /sys/module/hid_magicmouse/parameters/scroll_speed [param_set_scroll_speed]"
/data/local/tmp/kflattest WRITE "/sys/module/hid_magicmouse/parameters/scroll_speed" "0"

echo "[143/205] WRITE: /dev/null [write_null]"
/data/local/tmp/kflattest WRITE "/dev/null" "0"

echo "[144/205] WRITE: /sys/kernel/tracing/instances/wifi/events/mac80211/drv_configure_filter/filter [event_filter_write]"
/data/local/tmp/kflattest WRITE "/sys/kernel/tracing/instances/wifi/events/mac80211/drv_configure_filter/filter" "0"

echo "[145/205] WRITE: /sys/kernel/slab/jbd2_revoke_record_s/reclaim_account [reclaim_account_store]"
/data/local/tmp/kflattest WRITE "/sys/kernel/slab/jbd2_revoke_record_s/reclaim_account" "0"

echo "[146/205] WRITE: /sys/module/overlay/parameters/redirect_max [param_set_ushort]"
/data/local/tmp/kflattest WRITE "/sys/module/overlay/parameters/redirect_max" "0"

echo "[147/205] WRITE: /sys/devices/virtual/mac80211_hwsim/hwsim0/ieee80211/phy0/rfkill0/soft [soft_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/mac80211_hwsim/hwsim0/ieee80211/phy0/rfkill0/soft" "0"

echo "[148/205] WRITE: /sys/devices/platform/dummy_hcd.0/usb1/avoid_reset_quirk [avoid_reset_quirk_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/dummy_hcd.0/usb1/avoid_reset_quirk" "0"

echo "[149/205] WRITE: /sys/devices/virtual/block/ram13/queue/write_cache [queue_wc_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/block/ram13/queue/write_cache" "0"

echo "[150/205] WRITE: /sys/kernel/tracing/error_log [tracing_err_log_write]"
/data/local/tmp/kflattest WRITE "/sys/kernel/tracing/error_log" "0"

echo "[151/205] WRITE: /sys/kernel/slab/net_namespace/poison [poison_store]"
/data/local/tmp/kflattest WRITE "/sys/kernel/slab/net_namespace/poison" "0"

echo "[152/205] WRITE: /sys/fs/f2fs/features/verity [f2fs_attr_store]"
/data/local/tmp/kflattest WRITE "/sys/fs/f2fs/features/verity" "0"

echo "[153/205] WRITE: /sys/devices/virtual/mac80211_hwsim/hwsim0/net/wlan0/queues/tx-0/byte_queue_limits/limit_max [bql_set_limit_max]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/mac80211_hwsim/hwsim0/net/wlan0/queues/tx-0/byte_queue_limits/limit_max" "0"

echo "[154/205] WRITE: /sys/devices/virtual/net/tunl0/netdev_group [group_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/net/tunl0/netdev_group" "0"

echo "[155/205] WRITE: /sys/module/uvcvideo/parameters/clock [uvc_clock_param_set]"
/data/local/tmp/kflattest WRITE "/sys/module/uvcvideo/parameters/clock" "0"

echo "[156/205] WRITE: /config/usb_gadget/g1/idProduct [gadget_dev_desc_idProduct_store]"
/data/local/tmp/kflattest WRITE "/config/usb_gadget/g1/idProduct" "0"

echo "[157/205] WRITE: /dev/ppp [ppp_write]"
/data/local/tmp/kflattest WRITE "/dev/ppp" "0"

echo "[158/205] WRITE: /sys/devices/virtual/thermal/thermal_zone0/k_pu [k_pu_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/thermal/thermal_zone0/k_pu" "0"

echo "[159/205] WRITE: /sys/devices/uprobe/perf_event_mux_interval_ms [perf_event_mux_interval_ms_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/uprobe/perf_event_mux_interval_ms" "0"

echo "[160/205] WRITE: /sys/devices/virtual/mac80211_hwsim/hwsim0/net/wlan0/queues/tx-2/traffic_class [netdev_queue_attr_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/mac80211_hwsim/hwsim0/net/wlan0/queues/tx-2/traffic_class" "0"

echo "[161/205] WRITE: /sys/module/snd_hda_intel/parameters/bdl_pos_adj [param_array_set]"
/data/local/tmp/kflattest WRITE "/sys/module/snd_hda_intel/parameters/bdl_pos_adj" "0"

echo "[162/205] WRITE: /sys/devices/virtual/block/zram0/mem_limit [mem_limit_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/block/zram0/mem_limit" "0"

echo "[163/205] WRITE: /sys/kernel/mm/swap/vma_ra_enabled [vma_ra_enabled_store]"
/data/local/tmp/kflattest WRITE "/sys/kernel/mm/swap/vma_ra_enabled" "0"

echo "[164/205] WRITE: /sys/module/rcupdate/parameters/rcu_cpu_stall_suppress [param_set_int]"
/data/local/tmp/kflattest WRITE "/sys/module/rcupdate/parameters/rcu_cpu_stall_suppress" "0"

echo "[165/205] WRITE: /sys/devices/virtual/thermal/thermal_zone0/slope [slope_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/thermal/thermal_zone0/slope" "0"

echo "[166/205] WRITE: /sys/devices/virtual/block/zram0/disksize [disksize_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/block/zram0/disksize" "0"

echo "[167/205] WRITE: /sys/devices/platform/i8042/serio0/bind_mode [serio_set_bind_mode]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/i8042/serio0/bind_mode" "0"

echo "[168/205] WRITE: /sys/devices/system/machinecheck/machinecheck1/monarch_timeout [device_store_int]"
/data/local/tmp/kflattest WRITE "/sys/devices/system/machinecheck/machinecheck1/monarch_timeout" "0"

echo "[169/205] WRITE: /config/usb_gadget/g1/driver_match_existing_only [gadget_driver_match_existing_only_store]"
/data/local/tmp/kflattest WRITE "/config/usb_gadget/g1/driver_match_existing_only" "0"

echo "[170/205] WRITE: /sys/kernel/tracing/buffer_percent [buffer_percent_write]"
/data/local/tmp/kflattest WRITE "/sys/kernel/tracing/buffer_percent" "0"

echo "[171/205] WRITE: /sys/devices/platform/dummy_hcd.0/usb1/interface_authorized_default [interface_authorized_default_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/platform/dummy_hcd.0/usb1/interface_authorized_default" "0"

echo "[172/205] WRITE: /sys/module/binder/parameters/stop_on_user_error [binder_set_stop_on_user_error]"
/data/local/tmp/kflattest WRITE "/sys/module/binder/parameters/stop_on_user_error" "0"

echo "[173/205] WRITE: /sys/module/scsi_mod/parameters/max_luns [param_set_ullong]"
/data/local/tmp/kflattest WRITE "/sys/module/scsi_mod/parameters/max_luns" "0"

echo "[174/205] WRITE: /sys/kernel/slab/bio-2/store_user [store_user_store]"
/data/local/tmp/kflattest WRITE "/sys/kernel/slab/bio-2/store_user" "0"

echo "[175/205] WRITE: /sys/devices/cpu/rdpmc [set_attr_rdpmc]"
/data/local/tmp/kflattest WRITE "/sys/devices/cpu/rdpmc" "0"

echo "[176/205] WRITE: /config/usb_gadget/g1/UDC [gadget_dev_desc_UDC_store]"
/data/local/tmp/kflattest WRITE "/config/usb_gadget/g1/UDC" "0"

echo "[177/205] WRITE: /sys/devices/virtual/bdi/1:8/waiting_for_supplier [dev_attr_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/bdi/1:8/waiting_for_supplier" "0"

echo "[178/205] WRITE: /proc/pressure/io [psi_io_write]"
/data/local/tmp/kflattest WRITE "/proc/pressure/io" "0"

echo "[179/205] WRITE: /sys/module/fuse/parameters/max_user_bgreq [set_global_limit]"
/data/local/tmp/kflattest WRITE "/sys/module/fuse/parameters/max_user_bgreq" "0"

echo "[180/205] WRITE: /sys/devices/virtual/thermal/thermal_zone0/integral_cutoff [integral_cutoff_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/thermal/thermal_zone0/integral_cutoff" "0"

echo "[181/205] WRITE: /sys/devices/pci0000:00/0000:00:01.3/d3cold_allowed [d3cold_allowed_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/pci0000:00/0000:00:01.3/d3cold_allowed" "0"

echo "[182/205] WRITE: /sys/kernel/irq/61/type [kobj_attr_store]"
/data/local/tmp/kflattest WRITE "/sys/kernel/irq/61/type" "0"

echo "[183/205] WRITE: /sys/devices/virtual/net/sit0/queues/tx-0/byte_queue_limits/limit_min [bql_set_limit_min]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/net/sit0/queues/tx-0/byte_queue_limits/limit_min" "0"

echo "[184/205] WRITE: /sys/power/mem_sleep [mem_sleep_store]"
/data/local/tmp/kflattest WRITE "/sys/power/mem_sleep" "0"

echo "[185/205] WRITE: /sys/devices/virtual/net/ip6gre0/queues/tx-0/xps_rxqs [xps_rxqs_store]"
/data/local/tmp/kflattest WRITE "/sys/devices/virtual/net/ip6gre0/queues/tx-0/xps_rxqs" "0"

## Interface triggers for ioctl

echo "[186/205] IOCTL: /dev/snd/timer [snd_timer_user_ioctl]"
/data/local/tmp/kflattest IOCTL "/dev/snd/timer" "0"

echo "[187/205] IOCTL: /mnt/user/0/emulated/0/Music/.thumbnails/.nomedia [fuse_file_ioctl]"
/data/local/tmp/kflattest IOCTL "/mnt/user/0/emulated/0/Music/.thumbnails/.nomedia" "0"

echo "[188/205] IOCTL: /proc/bus/pci/00/06.0 [proc_bus_pci_ioctl]"
/data/local/tmp/kflattest IOCTL "/proc/bus/pci/00/06.0" "0"

echo "[189/205] IOCTL: /dev/hpet [hpet_ioctl]"
/data/local/tmp/kflattest IOCTL "/dev/hpet" "0"

echo "[190/205] IOCTL: /dev/tun [tun_chr_ioctl]"
/data/local/tmp/kflattest IOCTL "/dev/tun" "0"

echo "[191/205] IOCTL: /dev/uinput [uinput_ioctl]"
/data/local/tmp/kflattest IOCTL "/dev/uinput" "0"

echo "[192/205] IOCTL: /dev/input/event1 [evdev_ioctl]"
/data/local/tmp/kflattest IOCTL "/dev/input/event1" "0"

echo "[193/205] IOCTL: /dev/snd/pcmC0D0c [snd_pcm_ioctl]"
/data/local/tmp/kflattest IOCTL "/dev/snd/pcmC0D0c" "0"

echo "[194/205] IOCTL: /dev/block/vde1 [block_ioctl]"
/data/local/tmp/kflattest IOCTL "/dev/block/vde1" "0"

## Interface triggers for mmap

echo "[195/205] MMAP: /dev/bus/usb/001/001 [usbdev_mmap]"
/data/local/tmp/kflattest MMAP "/dev/bus/usb/001/001" "0"

echo "[196/205] MMAP: /sys/devices/pci0000:00/0000:00:04.0/resource1 [pci_mmap_resource_uc]"
/data/local/tmp/kflattest MMAP "/sys/devices/pci0000:00/0000:00:04.0/resource1" "0"

echo "[197/205] MMAP: /dev/zero [mmap_zero]"
/data/local/tmp/kflattest MMAP "/dev/zero" "0"

echo "[198/205] MMAP: /dev/snd/pcmC0D0c [snd_pcm_mmap]"
/data/local/tmp/kflattest MMAP "/dev/snd/pcmC0D0c" "0"

echo "[199/205] MMAP: /dev/binderfs/hwbinder [binder_mmap]"
/data/local/tmp/kflattest MMAP "/dev/binderfs/hwbinder" "0"

echo "[200/205] MMAP: /proc/bus/pci/00/16.0 [proc_bus_pci_mmap]"
/data/local/tmp/kflattest MMAP "/proc/bus/pci/00/16.0" "0"

echo "[201/205] MMAP: /sys/devices/pci0000:00/0000:00:12.0/resource4_wc [pci_mmap_resource_wc]"
/data/local/tmp/kflattest MMAP "/sys/devices/pci0000:00/0000:00:12.0/resource4_wc" "0"

echo "[202/205] MMAP: /dev/ashmem3aeba122-ea28-4a94-a184-61103c9972f3 [ashmem_mmap]"
/data/local/tmp/kflattest MMAP "/dev/ashmem3aeba122-ea28-4a94-a184-61103c9972f3" "0"

echo "[203/205] MMAP: /dev/hpet [hpet_mmap]"
/data/local/tmp/kflattest MMAP "/dev/hpet" "0"

echo "[204/205] MMAP: /sys/fs/selinux/policy [sel_mmap_policy]"
/data/local/tmp/kflattest MMAP "/sys/fs/selinux/policy" "0"

echo "[205/205] MMAP: /sys/fs/selinux/status [sel_mmap_handle_status]"
/data/local/tmp/kflattest MMAP "/sys/fs/selinux/status" "0"

