#!/bin/bash

cp -f staging/lib/modules/5.4.86/kernel/drivers/cpufreq/dummy-cpufreq.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/net/core/failover.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/extra/goldfish_drivers/goldfish_sync.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/extra/goldfish_drivers/goldfish_address_space.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/extra/goldfish_drivers/goldfish_battery.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/extra/goldfish_drivers/goldfish_pipe.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/fs/incfs/incrementalfs.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/drivers/net/wireless/mac80211_hwsim.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/drivers/md/md-mod.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/drivers/nvdimm/nd_virtio.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/drivers/net/net_failover.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/drivers/rtc/rtc-test.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/sound/pci/hda/snd-hda-codec-generic.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/sound/pci/hda/snd-hda-intel.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/sound/pci/hda/snd-hda-codec.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/sound/pci/hda/snd-hda-codec-realtek.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/sound/hda/snd-hda-core.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/sound/hda/snd-intel-nhlt.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/lib/test_meminit.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/lib/test_stackinit.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/drivers/block/virtio_blk.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/drivers/char/virtio_console.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/extra/virtio_gpu/virtio-gpu.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/drivers/virtio/virtio_input.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/drivers/virtio/virtio_mmio.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/drivers/net/virtio_net.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/drivers/virtio/virtio_pci.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/drivers/nvdimm/virtio_pmem.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
cp -f staging/lib/modules/5.4.86/kernel/drivers/char/hw_random/virtio-rng.ko $ANDROID_DIR/prebuilts/qemu-kernel/x86_64/5.4/ko
